/* ============================================================================
 * TABLE: GOLDEN_IMAGE
 * PURPOSE:
 *   Managed Service별 "골든 컨테이너 이미지"를 단일 테이블로 관리.
 *   - Harbor(또는 호환 Registry) 내 repository 경로 + tag/digest 기반으로 이미지 참조를 저장
 *   - 서비스/컴포넌트별 활성(현재 적용) 골든 이미지를 1개로 강제
 *   - 이미지별 추가 속성(props)을 JSON으로 저장
 *
 * IMAGE_REF 구성 예시:
 *   - tag 기반   : {REGISTRY_HOST}/{PROJECT_NAME}/{REPO_NAME}:{IMAGE_TAG}
 *   - digest 기반: {REGISTRY_HOST}/{PROJECT_NAME}/{REPO_NAME}@{IMAGE_DIGEST}
 * ============================================================================ */

CREATE TABLE GOLDEN_IMAGE (
  /* PK (대체키) */
  GOLDEN_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  /* 서비스 식별 */
  SERVICE_ID       VARCHAR2(50)  NOT NULL,                 -- 플랫폼 내부 서비스 식별자
  COMPONENT        VARCHAR2(50)  DEFAULT 'default' NOT NULL,-- 서비스 내 컴포넌트(api/worker/ui). 단일이면 default

  /* 레지스트리/리포지토리(하버) 경로 */
  REGISTRY_HOST    VARCHAR2(255) NOT NULL,                 -- ex) harbor.example.com
  PROJECT_NAME     VARCHAR2(200) NOT NULL,                 -- harbor project (namespace) ex) my-project
  REPO_NAME        VARCHAR2(200) NOT NULL,                 -- repository name ex) langflow-api

  /* 아티팩트 식별자 (둘 중 하나는 반드시 존재) */
  IMAGE_TAG        VARCHAR2(200),                          -- ex) 1.2.3, latest (가변 가능)
  IMAGE_DIGEST     VARCHAR2(200),                          -- ex) sha256:... (불변 권장)

  /* 추가 속성(JSON) */
  PROPS            CLOB,                                   -- JSON 저장(예: 보안스캔, 메모, labels 등)

  /* 운영 메타 */
  IS_ACTIVE        CHAR(1)       DEFAULT 'Y' NOT NULL,     -- 현재 적용중인 골든 여부(Y/N)
  CREATED_BY       VARCHAR2(100) NOT NULL,                 -- 생성자
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY       VARCHAR2(100),                          -- 수정자
  UPDATED_AT       TIMESTAMP,                              -- 수정일시

  /* 편의 필드: 실제 배포에 사용할 이미지 참조 문자열(캐시/직접사용) */
  IMAGE_REF        VARCHAR2(1000),                         -- ex) harbor.../proj/repo:tag or @sha256...

  /* 제약조건 */
  CONSTRAINT PK_GOLDEN_IMAGE PRIMARY KEY (GOLDEN_ID),

  -- tag 또는 digest 둘 중 하나는 반드시 존재해야 함
  CONSTRAINT CK_GOLDEN_IMAGE_TAG_OR_DIGEST
    CHECK (IMAGE_TAG IS NOT NULL OR IMAGE_DIGEST IS NOT NULL),

  -- 활성값은 Y/N만 허용
  CONSTRAINT CK_GOLDEN_IMAGE_ACTIVE
    CHECK (IS_ACTIVE IN ('Y','N')),

  -- PROPS는 JSON만 허용 (NULL 허용)
  CONSTRAINT CK_GOLDEN_IMAGE_PROPS_JSON
    CHECK (PROPS IS NULL OR PROPS IS JSON)
);

-- 서비스/컴포넌트별 "활성(Y) 골든 이미지 1개" 강제 (Oracle Partial Unique Index)
CREATE UNIQUE INDEX UQ_GOLDEN_IMAGE_ACTIVE_ONE
  ON GOLDEN_IMAGE (SERVICE_ID, COMPONENT)
  WHERE IS_ACTIVE = 'Y';

-- 조회 최적화 인덱스
CREATE INDEX IX_GOLDEN_IMAGE_SVC
  ON GOLDEN_IMAGE (SERVICE_ID, COMPONENT);

CREATE INDEX IX_GOLDEN_IMAGE_REPO
  ON GOLDEN_IMAGE (REGISTRY_HOST, PROJECT_NAME, REPO_NAME);


/* ============================================================================
 * COMMENTS
 * ============================================================================ */

COMMENT ON TABLE GOLDEN_IMAGE IS
'Managed Service별 골든 컨테이너 이미지 관리 테이블. Harbor repo 경로 + tag/digest 기반 이미지 참조 및 JSON props 저장. 서비스/컴포넌트별 활성 골든 1개를 강제함.';

COMMENT ON COLUMN GOLDEN_IMAGE.GOLDEN_ID IS
'골든 이미지 레코드 PK(대체키, IDENTITY).';

COMMENT ON COLUMN GOLDEN_IMAGE.SERVICE_ID IS
'플랫폼 내부 서비스 식별자.';

COMMENT ON COLUMN GOLDEN_IMAGE.COMPONENT IS
'서비스 내 컴포넌트 식별자(api/worker/ui 등). 단일이면 default.';

COMMENT ON COLUMN GOLDEN_IMAGE.REGISTRY_HOST IS
'컨테이너 레지스트리 호스트(예: harbor.example.com).';

COMMENT ON COLUMN GOLDEN_IMAGE.PROJECT_NAME IS
'레지스트리 프로젝트/네임스페이스(예: my-project).';

COMMENT ON COLUMN GOLDEN_IMAGE.REPO_NAME IS
'레지스트리 리포지토리명(예: langflow-api).';

COMMENT ON COLUMN GOLDEN_IMAGE.IMAGE_TAG IS
'이미지 태그(가변 가능, 예: 1.2.3, latest). IMAGE_DIGEST와 함께 사용 가능하며 둘 중 하나는 필수.';

COMMENT ON COLUMN GOLDEN_IMAGE.IMAGE_DIGEST IS
'이미지 다이제스트(불변 권장, 예: sha256:...). IMAGE_TAG와 함께 사용 가능하며 둘 중 하나는 필수.';

COMMENT ON COLUMN GOLDEN_IMAGE.PROPS IS
'이미지별 추가 속성(JSON). 예: 보안스캔 결과, 메모, labels/annotations, 배포 정책 등. CLOB + IS JSON 제약.';

COMMENT ON COLUMN GOLDEN_IMAGE.IS_ACTIVE IS
'현재 적용(활성) 골든 여부(Y/N). 서비스/컴포넌트별 활성(Y) 레코드는 1개로 제한.';

COMMENT ON COLUMN GOLDEN_IMAGE.CREATED_BY IS
'레코드 생성자(계정/사용자/시스템 식별).';

COMMENT ON COLUMN GOLDEN_IMAGE.CREATED_AT IS
'레코드 생성 일시.';

COMMENT ON COLUMN GOLDEN_IMAGE.UPDATED_BY IS
'레코드 수정자(계정/사용자/시스템 식별).';

COMMENT ON COLUMN GOLDEN_IMAGE.UPDATED_AT IS
'레코드 수정 일시.';

COMMENT ON COLUMN GOLDEN_IMAGE.IMAGE_REF IS
'배포에 사용할 전체 이미지 참조 문자열(예: harbor.../proj/repo:tag 또는 @sha256...). 필요 시 캐시/직접사용.';